# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: GITHUB Node.js Package

on:
  push:
    branches:
      - main
  workflow_dispatch:
    # Manual trigger from GitHub UI, but will only run fully on the release branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm test

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build

      ## update pacakge json name to include scope
      - name: Update package name with scope
        run: |
          PACKAGE_JSON="package.json"
          PACKAGE_NAME=$(jq -r '.name' $PACKAGE_JSON)
          SCOPE="@juji"
          if [[ $PACKAGE_NAME != $SCOPE/* ]]; then
            NEW_PACKAGE_NAME="$SCOPE/$PACKAGE_NAME"
            jq --arg name "$NEW_PACKAGE_NAME" '.name = $name' $PACKAGE_JSON > tmp.$$.json && mv tmp.$$.json $PACKAGE_JSON
            echo "Updated package name to $NEW_PACKAGE_NAME"
            cat $PACKAGE_JSON
          else
            echo "Package name already includes scope."
          fi
      - run: npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
