# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - release
  workflow_dispatch:
    # Manual trigger from GitHub UI, but will only run fully on the release branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify release branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/release" ]]; then
            echo "⚠️ This workflow should only be run on the release branch"
            echo "Current branch: ${GITHUB_REF#refs/heads/}"
            exit 1
          else
            echo "✅ On release branch, proceeding with build"
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      - run: npm test

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Verify release branch
        run: |
          if [[ "${{ github.ref }}" != "refs/heads/release" ]]; then
            echo "⚠️ This workflow should only be run on the release branch"
            echo "Current branch: ${GITHUB_REF#refs/heads/}"
            exit 1
          else
            echo "✅ On release branch, proceeding with build"
          fi
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
